# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名称'),
        ),
    ]
