# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181010_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生日'),
        ),
    ]
